env:
  - COSIGN_YES=true

before:
  hooks:
    - go mod tidy
project_name: ccr
builds:
  - binary: ccr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Other'
      order: 999
sboms:
 - artifacts: archive
signs:
  - id: keyless
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: all
brews:
  - name: codecatalyst-runner-cli

    # GitHub/GitLab repository to push the formula to
    tap:
      owner: aws
      name: homebrew-tap

    url_template: "https://github.com/aws/codecatalyst-runner-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: codecatalyst-runner-cli
      email: codecatalyst-runner-cli@no-reply.github.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    homepage: "https://github.com/aws/codecatalyst-runner-cli"

    # Template of your app's description.
    # Default is empty.
    description: "CLI to run CodeCatalyst workflows locally 🧰"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: true

    # So you can `brew test` your formula.
    # Default is empty.
    test: system "#{bin}/ccr --version"
