name: release-codecatalyst-runner
on:
  push:
    tags:
      - 1.*.*
      - 0.*.*

env:
  CGO_ENABLED: 0
  AWS_REGION: us-east-1

permissions:
  contents: write
  id-token: write

defaults:
  run:
    working-directory: codecatalyst-runner

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.work
          check-latest: true
          cache-dependency-path: "**/go.sum"
      - uses: anchore/sbom-action/download-syft@v0.14.3
      - uses: sigstore/cosign-installer@v3
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
          workdir: codecatalyst-runner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: codecatalyst-runner/dist/
